next.config.js
src/components/nav/bottomNav/BottomNav.tsx
src/components/profile/ProfileFeedList.tsx
src/hooks/useInfinityScroll.ts
src/hooks/useInfinityScroll.tsx
src/hooks/useIsScrolling.ts
src/pages/[username]/feed/index.tsx
src/pages/feed/index.tsx

무한스크롤 커스텀 훅 만들기
* useInfiniteQuery를 사용하는 무한스크롤 동작 부분이 반복되는 코드가 많고 앞으로도 재사용 가능성을 고려하여 커스텀 훅으로 분리함
```ts
// src/hooks/useInfinityScroll.ts
export const useInfinityScroll = (
FeedDataClassification: string,
username?: string | string[] | undefined,
) => {
const bottom = useRef<HTMLDivElement>(null);
const FetchFeedData = (
FeedDataClassification: string,
pageParam: number,
username?: string | string[] | undefined,
) => {
if (FeedDataClassification === 'newFeeds') {
return FeedService.getFeeds({
page: pageParam,
limit: 10,
});
}
if (FeedDataClassification === 'myFeeds') {
return FeedService.findAllByUser(username, {
page: pageParam,
limit: 10,
});
}
if (FeedDataClassification === 'bookmark') {
if (username) {
return FeedService.findAllByUser(username, {
page: pageParam,
limit: 10,
});
}
}
}; …
```

refactor: 무한스크롤 커스텀 훅 생성하기

---

src/hooks/useInfinityScroll.ts
src/pages/feed/index.tsx

서버 데이터 아무것도 없을때 스피너 깜빡현상, 무한 데이터 요청 버그 수정

fix: 무한요청 에러 수정

---

src/components/feed/FeedItem.tsx

피드 삭제후 목록 쿼리 불러오기
react query mutate형태로 변경 -> muteAsync 로 작업시 성공시에 대한 로직 작동이 안됨 (이유는 아직 파악 불가)
- 기존 코드
```tsx
const { mutateAsync, isLoading } = useMutation((feedId: number) => {
if (feedId !== undefined) {
return FeedService.deleteFeed(feedId);
}
return Promise.reject(new Error('피드가 존재하지 않습니다'));
});
const handleDeleteFeedItem = async (feedId: number) => {
try {
await mutateAsync(feedId);
setIsModalOpen(false);
return queryClient.invalidateQueries(['feeds']);
} catch (error: any) {
console.log('error?.response', error?.response);
}
};
```
- 변경 코드 
```tsx
const deleteFeedItemMutation = useMutation({
mutationKey: ['delete-feed', item.id],
mutationFn: (feedId: number) => FeedService.deleteFeed(feedId),
onSuccess: () => {
setIsModalOpen(false);
return …
```

refactor: 피드 삭제후 목록 쿼리 불러오기

---

src/components/feed/FeedItem.tsx
src/components/layouts/ProfileLayout.tsx
src/components/nav/bottomNav/BottomNav.tsx
src/pages/[username]/edit/index.tsx
src/services/user/index.ts

유저별 피드목록 API 경로 수정으로 관련 컴포넌트 리팩토링 
- 프로필 페이지
-  router 경로에서 username 추출해서 피드 쿼리 불러오기   
-  본인 프로필에서만 `로그아웃` 및 `편집` 버튼 보이게 조건문 적용
```tsx
const ProfileLayout = ({ children }: BaseProps) => {
const router = useRouter();
const [username, _] = useLocalStorage('username', '');
const setUser = useSetRecoilState(userState);
const { data: profile } = useQuery(['user', router.query.username], () =>
UserService.findUserByUsername(
(router.query.username as string) || username,
),
);
(...생략...)
return (
<>
<TopHeader>
<TopHeader.Left>
<button onClick={() => router.back()}>뒤로</button>
</TopHeader.Left>
<TopHeader.Title>
<h1 className="blind">프로필</h1>
</TopHeader.Title>
<TopHeader.Right>
{/* ======== 조건문 적용 ========  */}
{profile && (
<>
{username === profile.username && (
<button onClick={() => …
```

refactor: 유저별 피드 목록 및 아이템  / 프로필 페이지 리팩토링

---

src/components/explore/ExploreUserListItem.tsx
src/components/my-profile/MyProfileInfo.tsx
src/components/nav/topHeader/TopHeader.tsx
src/components/profile/ProfileCount.tsx
src/core/types/user/user.interface.ts
src/pages/settings/account-status/index.tsx
src/pages/settings/index.tsx
src/pages/settings/my-profile/index.tsx
src/styles/globals.scss

나의 프로필 상세 정보 페이지 추가
| 내 정보 상세 | 프로필 편집 이동 |
| --- | --- | 
| ![google_screen_recording_2023-11-05T13-04_28 713Z](https://github.com/PlaNet-Devteam/sns-project-client/assets/52031484/9665f1ff-fbe0-44b0-88ac-fcd5d2671996) | <img src="https://github.com/PlaNet-Devteam/sns-project-client/assets/52031484/bcb96bd9-09c0-414b-af57-6c0efa40824d" width="376" /> |

feat: 나의 프로필 상세 정보 페이지 추가

---

src/components/feed/FeedItem.tsx
src/components/profile/ProfileFeedList.tsx
src/core/types/feed/feed-list.interface.ts
src/core/types/feed/feed.interface.ts
src/services/feed/index.ts

마이피에지 북마크 피드 목록 및 추가 & 해제 기능 추가
| 북마크 추가&해제 | 북마크 피드 목록 |
| --- | --- | 
| ![google_screen_recording_2023-11-05T16-36_39 295Z](https://github.com/PlaNet-Devteam/sns-project-client/assets/52031484/f6efc15c-f628-468f-9f6b-0d52db40acd3) | ![google_screen_recording_2023-11-05T16-37_37 257Z](https://github.com/PlaNet-Devteam/sns-project-client/assets/52031484/0984956a-800f-4727-9fd8-2b3e07f6c29a) |
- 북마크 추가 및 해제 
- `feed_id` 값을 전달하여 서버에서 `user_id` 값과 함께 bookmark 테이블에 저장 및 삭제
```tsx
const FeedItem = ({ item }: FeedItemProps) => {
(...생략...)
const bookmarkFeedItemMutation = useMutation({
mutationKey: ['bookmark-feed', item.id],
mutationFn: (feedId: number) => FeedService.bookmarkFeed(feedId),
onSuccess: () => {
return queryClient.invalidateQueries(['feeds']);
},
});
const …
```

feat: 마이피에지 북마크 피드 목록 및 추가 & 해제 기능 추가

---

src/components/common/UserProfileImage.module.scss
src/components/explore/ExploreFeedList.tsx
src/components/explore/ExploreTagInfo.tsx
src/components/explore/ExploreUserList.tsx
src/components/follow/FollowListItem.tsx
src/components/profile/ProfileCount.tsx
src/components/profile/ProfileFeedTabs.tsx
src/components/profile/ProfileImage.tsx
src/pages/explore/feed/tags/[tagName]/index.tsx
src/services/feed/index.ts
src/styles/components/profile/_profile-feed-tabs.scss

유저 조회 및 피드 조회 시 차단 유저 체외 처리 추가
- 서버에서 차단 유저에 관한 로직 리팩토링 후 반영
- 팔로잉&팔로우 목록에서 본인 정보 가장 상단에 노출
`@lalisa` 라는 유저의 팔로워&팔로잉 목록을 확인할때, 각각 4명의 유저는 필터링 되는 조건에 의해 다르게 보이게 된다 
| 유저 프로필 |
| --- |
| ![image](https://github.com/PlaNet-Devteam/sns-project-client/assets/52031484/d618e427-03a1-49d4-ab74-728c6c4da6da) |
|    |  USER 1  |  USER 2   |  USER 3 |  USER4 |
| --- | :---: | :---: | :---: | :---: |
| | ![image](https://github.com/PlaNet-Devteam/sns-project-client/assets/52031484/e55c36ef-a82d-4cbe-a308-cd947c2a9343) | <img src="https://github.com/PlaNet-Devteam/sns-project-client/assets/52031484/732a8f99-e701-4623-8be7-643aaaea84d0" width="360" /> | ![image](https://github.com/PlaNet-Devteam/sns-project-client/assets/52031484/acbf0b7d-087e-427b-8469-21f4f73aa945) | …

refactor: 유저 조회 및 피드 조회 시 차단 유저 체외 처리 추가

---

src/components/layouts/ProfileLayout.tsx
src/pages/login/index.tsx

useGoogleLogin 구글 로그인 로직 적용
- useGoogleLogin 훅 적용
- 로그인 후 onSuccess 콜백 로직 추가
- 코드가 간단한 로직이여서 제가 기존에 작업했던거 추가하여 커밋하였습니다
- 참고만 해주시고 채팅방 작업 계속 진행해주세요 !

feat: useGoogleLogin 구글 로그인 로직 적용

---

.gitignore
next.config.js

docs: next.config.js 수정

---

src/pages/index.tsx

feat: meta 태그 http-equiv 추가
* 
*

feat: meta 태그 http-equiv 추가

---

next.config.js
src/pages/_document.tsx

fix: document에 meta태그 추가

---

next.config.js

docs: rerwrites() 옵션 제거

---

next.config.js

domain 주소 추가
배포용 도메인 next.config.js 추가

docs: domain 주소 추가

---

next.config.js

docs: 불필요 설정 제거

---

package.json
src/components/direct-message/DirectMessageList.module.scss
src/components/direct-message/DirectMessageList.tsx
src/components/direct-message/DirectMessageUserListItem.tsx
src/contexts/SocketContext.tsx
src/hooks/index.ts
src/hooks/useSocket.ts
src/pages/_app.tsx
src/pages/_document.tsx
src/pages/direct/inbox/index.tsx
src/pages/direct/new/index.tsx
src/pages/index.tsx
yarn.lock

socket  SocektProvider 및 useSocket 커스텀 훅 추가
- ContextApi 로 SocektProvider 및 useSocket 커스텀 훅 추가하여 socket 전역으로 사용하도록 변경
- meta 태그 불필요 코드 삭제

refactor: socket SocektProvider 및 useSocket 커스텀 훅 추가

---

src/pages/_document.tsx

fix: Head 태그 수정

---

src/components/direct-message/DirectMessageList.tsx
src/components/direct-message/DirectMessageUserListItem.tsx
src/pages/_app.tsx
src/pages/direct/inbox/index.tsx
src/pages/direct/new/index.tsx
src/styles/components/nav/_bottom_nav.scss

test: 소켓 테스트 주석

---

README.md

docs: udpate RAEDME.md

---

src/components/common/form/InputField.tsx
src/components/dialog/Dialog.tsx
src/components/dialog/DialogHeader.module.scss
src/components/dialog/DialogHeader.tsx
src/components/explore/ExploreTagInfo.tsx
src/components/feed/FeedItem.tsx
src/components/feed/FeedItemActionButtons.tsx
src/components/feed/FeedItemCountInfo.tsx
src/components/feed/FeedShareModal.tsx
src/components/layouts/BaseLayout.tsx
src/components/layouts/ProfileLayout.tsx
src/components/metatag/MetaTag.tsx
src/components/nav/topHeader/TopHeader.tsx
src/components/profile/ProfileFeedModal.tsx
src/core/base.service.ts
src/hooks/index.ts
src/hooks/useAuth.ts
src/hooks/useIsMobile.ts
src/pages/_app.tsx
src/pages/explore/feed/tags/[tagName]/index.tsx
src/pages/feed/[id]/index.tsx
src/services/feed/index.ts
src/store/feedAtom.ts

피드 상세 및 공유하기 버튼 추가
- 피드 상세 페이지 추가
- 피드 공유 모달 추가
- 로그인 상태에 따른 조건 리팩토링
- 호출되는 API가 달라짐 (사용자 인증 정보가 포함되냐 안되냐)   
- recoil 로 모달 전역상태 관리
```tsx
const setFeedShareModal = useSetRecoilState(feedShareModalState);
const setIsFeedShareModalOpen = useSetRecoilState(isFeedShareModalOpenState);
const onClickShareHandler = () => {
if (isMobile) {
navigator.share({
text: item.description,
title: `${item.user.username} 님의 피드`,
url: `${process.env.NEXT_PUBLIC_SITE_URL}feed/${item.id}`,
});
} else {
setFeedShareModal(item);
setIsFeedShareModalOpen(true);
}
};
```
closes #122 
*

feat: 피드 상세 및 공유하기 버튼 추가

---

src/components/common/FeedModal.module.scss
src/components/feed/Carousel.module.scss

carousel 스타일 수정
- carousel 가운데 정렬
- carousel 이미지 배경색 지정
close #121

style: carousel 스타일 수정

---

src/components/explore/ExploreUserList.tsx
src/components/explore/ExploreUserListItem.tsx

사용자 탐색 버그 수정 및 유저명 링크 추가
- payload 조건 추가 및 유저명 링크 추가

fix: 사용자 탐색 버그 수정 및 유저명 링크 추가

---

src/components/common/FeedModal.module.scss
src/components/feed/Carousel.module.scss
src/components/feed/Carousel.tsx
src/components/feed/FeedImg.module.scss

feed 및 feedModal 관련 css 수정
- 피드 목록 이미지 및 피드 모달 관련 css 수정
- 이미지의 비율 및 넓이 높이 관련 수정

style: feed 및 feedModal 관련 css 수정

---

src/components/feed/FeedItemActionButtons.tsx
src/pages/feed/[id]/index.tsx

meta태그 및 navagater.share 텍스트 내용 수정
- getServerSideProps 로 서버사이드로 데이터 가져오기
- meta태그 og 적용
```tsx
const FeedDetail = ({ initialFeed }: FeedDetailProps) => {
const router = useRouter();
const { payload } = useAuth();
const myInfo = useRecoilValue(userState);
const feedId = router.query.id as string;
const { data: feed, refetch } = useQuery(['feed-detail', feedId], () => {
if (feedId) {
if (myInfo || payload) {
return FeedService.getFeedByUser(parseInt(feedId));
} else {
return FeedService.getFeed(parseInt(feedId));
}
}
});
useEffect(() => {
if (myInfo) {
refetch();
}
}, [myInfo, refetch]);
return (
<>
{initialFeed && (
<MetaTag
title={`[PlaNet SNS] ${initialFeed.user.username}님의 피드`}
url={`${process.env.NEXT_PUBLIC_SITE_URL}feed/${initialFeed.id}`}
description={initialFeed?.description} …
```

fix: meta태그 및 navagater.share 텍스트 내용 수정

---

src/components/layouts/ProfileLayout.tsx
src/components/nav/topHeader/TopHeader.tsx
src/hooks/useAuth.ts
src/pages/feed/[id]/index.tsx

payload 관련 버그 수정
payload에서 가져온 정보로 렌더링시 클라이언트와 서버간의 렌더링 구조가 달라서 생기는 버그 수정
recoil 에서 저장한 정보로 클라이언트에서 렌더링되도록 변경

refactor: payload 관련 버그 수정

---

src/components/comment/CommentInput.tsx
src/components/comment/CommentReplyInput.tsx
src/components/common/UserProfileImage.tsx
src/components/common/img/BaseImage.module.scss
src/components/common/img/BaseImage.tsx
src/components/common/img/ThumbImage.tsx
src/components/explore/ExploreTagInfo.tsx
src/components/feed/Carousel.tsx
src/components/feed/FeedImg.tsx
src/components/profile/ProfileFeedListItem.tsx
src/components/profile/ProfileImage.tsx
src/pages/feed/modify/index.tsx
src/pages/message/userlist/index.tsx
src/styles/components/profile/_profile-info.scss

이미지 컴포넌트 공통 처리를 위한 리팩토링
- <Image / > 컴포넌트들을 공통적으로 처리하기위한 컴포넌트 작업
- 파편화 되어있던 부분을 한 컴포넌트에서 처리하게끔 작업
```tsx
interface BaseImageProps extends BaseProps {
src: string;
width: number;
height: number;
alt: string;
onError?: () => void;
draggable?: boolean;
}
const BaseImage = ({
src,
width,
height,
alt,
onError,
draggable,
className,
}: BaseImageProps) => {
return (
<div className={styles.container}>
<>
{src ? (
<Image
src={
isExternalImage(src)
? src
: `${process.env.NEXT_PUBLIC_AWS_S3_BUCKET}${src}`
}
width={width}
height={height}
alt={alt}
onError={onError}
className={classNames(styles.image, className)}
draggable={draggable}
placeholder="blur"
blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAFklEQVR42mN8//HLfwYiAOOoQvoqBABbWyZJf74GZgAAAABJRU5ErkJggg=="
/>
) …
```

refactor: 이미지 컴포넌트 공통 처리를 위한 리팩토링

---

next.config.js
src/components/feed/FeedImg.module.scss
src/pages/_app.tsx
src/pages/login/index.tsx
src/pages/signup/complete/index.tsx

QueryClient cacheTime 및 stalteTime 전역 옵션 추가 및 기타 수정
- QueryClient cacheTime 및 stalteTime 전역 옵션 추가
- 게스트 로그인 버튼 추가
- next.config.js s3 도메인 주소 추가
- 스타일 css 수정 및 클래스 추가

refactor: QueryClient cacheTime 및 stalteTime 전역 옵션 추가
